title: Jun의 게임 개발 이야기 
email: jun.gamedev@gmail.com
description: Jun's personal blog to share what he has learned.
permalink: ':title/'
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: https://skywhale22.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Junyoung Kim # add your name
author-pic: Profile/Me.png
about-author: 도전적이고, 창의적인 게임 개발자. 미국 소재 대학 휴학중. 현재 Beluga 엔진을 제작하며, 모바일 게임 '포포링 아일랜드'에서 프로그래머로써 참여하면서 산업기능요원을 준비하고 있음. Microsoft C++ MVP가 되는것과 C++ ISO에서 C++의 미래를 함께 만들어나가는것을 목표로 하고 있음.

# Contact links
email: jun.gamedev@gmail.com # Add your Email address
phone: 010-5143-6245 
website: jungamedev.github.io # Add your website, do not add http://
# linkedin: # Add your Linkedin handle
github: JunGameDev # Add your Github handle
twitter: '@Jun.GameDev' # Add your Twitter handle
facebook: kimsuit22 # Add your Facebook handle
instagram: jun_gamedev # Add your Instagram handle
# pinterest: # Add your Pinterest handle

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: JunGameDev-github-io # Add your discus identifier

# Tracker
# analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

sass:
    sass_dir: _sass
    style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json"]
# "assets/css/sass/"

